# Generated by Django 6.0.4 on 2026-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="conversation_key",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
