# Generated by Django 6.0.4 on 2026-05-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "conversations",
            "0003_alter_conversation_options_alter_message_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="conversations.conversation",
            ),
        ),
    ]
