# Generated by Django 6.0.4 on 2026-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0005_conversationinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="last_delivered_message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
