# Generated by Django 6.0.4 on 2026-05-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0006_participant_last_delivered_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationinvite",
            name="invite_count",
            field=models.IntegerField(default=0),
        ),
    ]
